# -*- coding: utf-8 -*-
"""Trabalho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10G9SJKetHXYEuLbJ-6kGfwLOiAs5bGBr
"""

import numpy as np
import pandas as pd
import plotly.express as px

df = pd.read_csv('https://raw.githubusercontent.com/IsaiasTy/salaries/main/salaries.csv')

df.head()

df.tail()

"""Grafico em Barras

"""

grouped_df = df.groupby(['work_year', 'employee_residence' , 'company_location' , 'salary'], sort=False).mean().reset_index()

px.bar(grouped_df, x='work_year', y='salary', color='employee_residence')

px.scatter(grouped_df, x='work_year', y='company_location', color='employee_residence')

px.bar(grouped_df, x='work_year', y='company_location', color='employee_residence')

grouped_df

